#!/usr/bin/env sh
set -eu

ROOT="${CODEX_HOME:-/home/d0mb1/.codex}"
SKILL_ROOT="${SKILL_ROOT:-$ROOT/skills}"

emit_header() {
  profile="$1"
  model="$2"
  effort="$3"
  out="$ROOT/$profile.config.toml"

  {
    printf "%s\n" "# Generated by scripts/generate_skill_profiles.sh. Local profile overlay."
    printf "%s\n" "# Launch with: codex --profile $profile"
    printf "model = \"%s\"\n" "$model"
    printf "model_reasoning_effort = \"%s\"\n" "$effort"
    printf "%s\n" "approval_policy = \"on-request\""
    printf "%s\n" "sandbox_mode = \"workspace-write\""
    printf "%s\n" "web_search = \"cached\""
    printf "\n%s\n" "[agents.subagent]"
    printf "%s\n" "model = \"cx/gpt-5.5-medium\""
  } > "$out"
}

append_disabled_skills() {
  profile="$1"
  allow_regex="$2"
  out="$ROOT/$profile.config.toml"

  find "$SKILL_ROOT" -mindepth 2 -maxdepth 2 -name SKILL.md ! -path "*/.system/*" | sort | while IFS= read -r skill; do
    name="$(basename "$(dirname "$skill")")"
    if printf "%s\n" "$name" | grep -Eq "$allow_regex"; then
      continue
    fi
    printf "\n%s\n" "[[skills.config]]" >> "$out"
    printf "path = \"%s\"\n" "$skill" >> "$out"
    printf "%s\n" "enabled = false" >> "$out"
  done
}

emit_profile() {
  profile="$1"
  model="$2"
  effort="$3"
  allow_regex="$4"
  emit_header "$profile" "$model" "$effort"
  append_disabled_skills "$profile" "$allow_regex"
}

MINIMAL="^(agents-md|caveman|caveman-help|caveman-review|source-driven-development|spec-driven-development|context-engineering|debugger|debugging-and-error-recovery|error-diagnostics-smart-debug|testing-patterns|test-driven-development|code-review-and-quality)$"
BUILD="^(agents-md|source-driven-development|spec-driven-development|incremental-implementation|test-driven-development|testing-patterns|debugger|debugging-and-error-recovery|code-review-and-quality|code-simplification|api-and-interface-design|api-design-principles|api-endpoint-builder|backend-architect|backend-dev-guidelines|backend-security-coder|frontend-developer|frontend-dev-guidelines|frontend-api-integration-patterns|javascript-pro|typescript-pro|nodejs-best-practices|bun-development|database|database-design|postgres-best-practices|security-and-hardening|security-audit)$"
RESEARCH="^(paper-lookup|academic-research-suite|literature-review|citation-management|scholar-evaluation|peer-review|scientific-writing|scientific-critical-thinking|scientific-brainstorming|pdf-conversion-router|pubmed-database|bgpt-paper-search|setting-up-reproducible-analysis|research-grants|latex-paper-conversion)$"
LINUX="^(linux-host-ops|linux-troubleshooting|linux-shell-scripting|bash-linux|bash-pro|bash-scripting|bash-defensive-patterns|posix-shell-pro|analyzing-linux-system-artifacts|analyzing-linux-audit-logs-for-intrusion|analyzing-persistence-mechanisms-in-linux|performing-linux-log-forensics-investigation|performing-disk-forensics-investigation|performing-network-forensics-with-wireshark|incident-responder|incident-runbook-templates|docker-expert|cloud-devops)$"
SECURITY="^(security-and-hardening|security-audit|security-auditor|security-bluebook-builder|security-requirement-extraction|security-scanning-security-dependencies|security-scanning-security-hardening|security-scanning-security-sast|api-security-best-practices|api-security-testing|web-security-testing|vulnerability-scanner|secrets-management|zeroize-audit|incident-responder|incident-response-smart-fix|conducting-api-security-testing|testing-api-security-with-owasp-top-10|testing-for-xss-vulnerabilities|implementing-secrets-scanning-in-ci-cd)$"
AGENT_DEV="^(agent-evaluation|agent-memory-mcp|agent-memory-systems|agent-orchestrator|agent-tool-builder|agentic-actions-auditor|agents-md|ai-agent-development|ai-agents-architect|ai-engineer|ai-engineering-toolkit|ai-native-cli|mcp-tool-developer|multi-agent-architect|context-engineering|context7-mcp|conversation-memory|hierarchical-agent-memory|llm-app-patterns|llm-prompt-optimizer|llm-structured-output|prompt-caching|prompt-engineering|rag-engineer|rag-implementation|skill-audit|skill-check|skill-creator-ms|skill-developer|skill-writer|skillopt-skill-optimizer|plugin-creator)$"
FRONTEND="^(frontend-developer|frontend-dev-guidelines|frontend-design|frontend-ui-engineering|frontend-ui-dark-ts|frontend-api-integration-patterns|react-best-practices|react-nextjs-development|react-patterns|react-ui-patterns|nextjs-app-router-patterns|nextjs-best-practices|astro|tailwind-design-system|tailwind-patterns|browser-testing-with-devtools|webwright|design-taste-frontend|accessibility-compliance-accessibility-audit|fixing-accessibility|javascript-pro|typescript-pro|bun-development)$"

emit_profile minimal "cx/gpt-5.5-medium" high "$MINIMAL"
emit_profile build "cx/gpt-5.5-medium" high "$BUILD"
emit_profile research "cx/gpt-5.5-xhigh" xhigh "$RESEARCH"
emit_profile linux "cx/gpt-5.5-medium" high "$LINUX"
emit_profile security "cx/gpt-5.5-xhigh" xhigh "$SECURITY"
emit_profile agent-dev "cx/gpt-5.5-xhigh" xhigh "$AGENT_DEV"
emit_profile frontend "cx/gpt-5.5-medium" high "$FRONTEND"

emit_header deep "cx/gpt-5.5-xhigh" xhigh

printf "%s\n" "Generated profiles in $ROOT: minimal build research linux security agent-dev frontend deep"
